"""Database design assistant package."""
"""
FORGE Prompts Module - XML Format
"""

from .knowledge import (
    DATABASE_FUNDAMENTALS_XML,
    DATA_TYPES_XML,
    INDEXING_XML,
    NORMALIZATION_XML,
    RELATIONSHIPS_XML,
    PERFORMANCE_XML,
    SECURITY_XML,
    ANTI_PATTERNS_XML,
    POSTGRESQL_XML,
    MYSQL_XML,
    MONGODB_XML,
    SQLITE_XML,
    SQLSERVER_XML,
    ORACLE_XML,
    MARIADB_XML,
    REDIS_XML,
    COMPLETE_KNOWLEDGE_XML,
)

from .patterns import (
    ECOMMERCE_XML,
    SOCIAL_XML,
    SAAS_XML,
    CONTENT_XML,
    MARKETPLACE_XML,
    COMMON_ENTITIES_XML,
    ALL_PATTERNS_XML,
)

from .agents import (
    CLASSIFIER_AGENT_XML,
    ARCHITECT_AGENT_XML,
    DATA_MODELER_AGENT_XML,
    OPTIMIZER_AGENT_XML,
    SQL_WRITER_AGENT_XML,
    REVIEWER_AGENT_XML,
    CHAT_AGENT_XML,
)

from .templates import (
    POSTGRESQL_TEMPLATE_XML,
    MYSQL_TEMPLATE_XML,
    MONGODB_TEMPLATE_XML,
    SQLITE_TEMPLATE_XML,
    SQLSERVER_TEMPLATE_XML,
    ORACLE_TEMPLATE_XML,
    MARIADB_TEMPLATE_XML,
    REDIS_TEMPLATE_XML,
)

__all__ = [
    "DATABASE_FUNDAMENTALS_XML",
    "DATA_TYPES_XML",
    "INDEXING_XML",
    "NORMALIZATION_XML",
    "RELATIONSHIPS_XML",
    "PERFORMANCE_XML",
    "SECURITY_XML",
    "ANTI_PATTERNS_XML",
    "POSTGRESQL_XML",
    "MYSQL_XML",
    "MONGODB_XML",
    "SQLITE_XML",
    "SQLSERVER_XML",
    "ORACLE_XML",
    "MARIADB_XML",
    "REDIS_XML",
    "COMPLETE_KNOWLEDGE_XML",
    "ECOMMERCE_XML",
    "SOCIAL_XML",
    "SAAS_XML",
    "CONTENT_XML",
    "MARKETPLACE_XML",
    "COMMON_ENTITIES_XML",
    "ALL_PATTERNS_XML",
    "CLASSIFIER_AGENT_XML",
    "ARCHITECT_AGENT_XML",
    "DATA_MODELER_AGENT_XML",
    "OPTIMIZER_AGENT_XML",
    "SQL_WRITER_AGENT_XML",
    "REVIEWER_AGENT_XML",
    "CHAT_AGENT_XML",
    "POSTGRESQL_TEMPLATE_XML",
    "MYSQL_TEMPLATE_XML",
    "MONGODB_TEMPLATE_XML",
    "SQLITE_TEMPLATE_XML",
    "SQLSERVER_TEMPLATE_XML",
    "ORACLE_TEMPLATE_XML",
    "MARIADB_TEMPLATE_XML",
    "REDIS_TEMPLATE_XML",
]