# generation/prompts/__init__.py
"""
System Prompts for Backend Generation
"""

from .master.master_prompt import MASTER_PROMPT

from .architecture import (
    ARCHITECTURE_PROMPTS,
    MICROSERVICES_PROMPT,
    MONOLITHIC_PROMPT,
    SERVERLESS_PROMPT,
    DDD_PROMPT,
    EVENT_DRIVEN_PROMPT,
    CQRS_PROMPT
)

from .api import (
    API_PROMPTS,
    REST_PROMPT,
    GRAPHQL_PROMPT,
    GRPC_PROMPT,
    VERSIONING_PROMPT,
    PAGINATION_PROMPT,
    RATE_LIMITING_PROMPT
)

from .database import (
    DATABASE_PROMPTS,
    SQL_PROMPT,
    NOSQL_PROMPT,
    SCHEMA_DESIGN_PROMPT,
    INDEXING_PROMPT,
    TRANSACTIONS_PROMPT,
    SHARDING_REPLICATION_PROMPT
)

from .security import (
    SECURITY_PROMPTS,
    OWASP_PROMPT,
    RBAC_PROMPT,
    ENCRYPTION_PROMPT,
    SECRETS_MANAGEMENT_PROMPT,
    VULNERABILITY_SCANNING_PROMPT
)

from .auth import (
    AUTH_PROMPTS,
    JWT_PROMPT,
    OAUTH2_PROMPT,
    SSO_PROMPT,
    MFA_PROMPT,
    LDAP_PROMPT,
    SESSION_MANAGEMENT_PROMPT
)

from .devops import (
    DEVOPS_PROMPTS,
    DOCKER_PROMPT,
    KUBERNETES_PROMPT,
    CICD_PROMPT,
    TERRAFORM_PROMPT,
    CLOUD_AWS_PROMPT,
    CLOUD_GCP_PROMPT,
    CLOUD_AZURE_PROMPT,
    MONITORING_PROMPT
)

from .performance import (
    PERFORMANCE_PROMPTS,
    SCALING_PROMPT,
    CACHING_PROMPT,
    LOAD_BALANCING_PROMPT,
    MESSAGE_QUEUE_PROMPT,
    DISASTER_RECOVERY_PROMPT
)

from .testing import (
    TESTING_PROMPTS,
    UNIT_TESTING_PROMPT,
    INTEGRATION_TESTING_PROMPT,
    E2E_TESTING_PROMPT,
    CONTRACT_TESTING_PROMPT,
    LOAD_TESTING_PROMPT,
    TDD_BDD_PROMPT
)

from .principles import (
    PRINCIPLES_PROMPTS,
    CLEAN_CODE_PROMPT,
    SOLID_PROMPT,
    DRY_KISS_YAGNI_PROMPT,
    DESIGN_PATTERNS_PROMPT
)

from .languages import (
    LANGUAGE_PROMPTS,
    TYPESCRIPT_PROMPT,
    PYTHON_PROMPT,
    GO_PROMPT,
    RUST_PROMPT,
    JAVA_PROMPT,
    CSHARP_PROMPT
)

from .frameworks import (
    FRAMEWORK_PROMPTS,
    EXPRESS_PROMPT,
    NESTJS_PROMPT,
    FASTAPI_PROMPT,
    DJANGO_PROMPT,
    GIN_PROMPT,
    SPRING_PROMPT,
    DOTNET_PROMPT
)

from .ml_inference import (
    ML_INFERENCE_PROMPTS,
    MODEL_SERVING_PROMPT,
    INFERENCE_OPTIMIZATION_PROMPT,
    RAG_PROMPT,
    VECTOR_DB_PROMPT
)

from .output.output_format_prompt import OUTPUT_FORMAT_PROMPT

__all__ = [
    "MASTER_PROMPT",
    "ARCHITECTURE_PROMPTS",
    "API_PROMPTS",
    "DATABASE_PROMPTS",
    "SECURITY_PROMPTS",
    "AUTH_PROMPTS",
    "DEVOPS_PROMPTS",
    "PERFORMANCE_PROMPTS",
    "TESTING_PROMPTS",
    "PRINCIPLES_PROMPTS",
    "LANGUAGE_PROMPTS",
    "FRAMEWORK_PROMPTS",
    "ML_INFERENCE_PROMPTS",
    "OUTPUT_FORMAT_PROMPT"
]