# generation/prompts/__init__.py
"""
System Prompts for Backend Generation
"""

from .api import (
    API_PROMPTS,
    GRAPHQL_PROMPT,
    GRPC_PROMPT,
    PAGINATION_PROMPT,
    RATE_LIMITING_PROMPT,
    REST_PROMPT,
    VERSIONING_PROMPT,
)
from .architecture import (
    ARCHITECTURE_PROMPTS,
    CQRS_PROMPT,
    DDD_PROMPT,
    EVENT_DRIVEN_PROMPT,
    MICROSERVICES_PROMPT,
    MONOLITHIC_PROMPT,
    SERVERLESS_PROMPT,
)
from .auth import (
    AUTH_PROMPTS,
    JWT_PROMPT,
    LDAP_PROMPT,
    MFA_PROMPT,
    OAUTH2_PROMPT,
    SESSION_MANAGEMENT_PROMPT,
    SSO_PROMPT,
)
from .database import (
    DATABASE_PROMPTS,
    INDEXING_PROMPT,
    NOSQL_PROMPT,
    SCHEMA_DESIGN_PROMPT,
    SHARDING_REPLICATION_PROMPT,
    SQL_PROMPT,
    TRANSACTIONS_PROMPT,
)
from .devops import (
    CICD_PROMPT,
    CLOUD_AWS_PROMPT,
    CLOUD_AZURE_PROMPT,
    CLOUD_GCP_PROMPT,
    DEVOPS_PROMPTS,
    DOCKER_PROMPT,
    KUBERNETES_PROMPT,
    MONITORING_PROMPT,
    TERRAFORM_PROMPT,
)
from .frameworks import (
    DJANGO_PROMPT,
    DOTNET_PROMPT,
    EXPRESS_PROMPT,
    FASTAPI_PROMPT,
    FLASK_PROMPT,
    FRAMEWORK_PROMPTS,
    GIN_PROMPT,
    NESTJS_PROMPT,
    SPRING_PROMPT,
)
from .languages import (
    CSHARP_PROMPT,
    GO_PROMPT,
    JAVA_PROMPT,
    LANGUAGE_PROMPTS,
    PYTHON_PROMPT,
    RUST_PROMPT,
    TYPESCRIPT_PROMPT,
)
from .master.master_prompt import MASTER_PROMPT
from .ml_inference import (
    INFERENCE_OPTIMIZATION_PROMPT,
    ML_INFERENCE_PROMPTS,
    MODEL_SERVING_PROMPT,
    RAG_PROMPT,
    VECTOR_DB_PROMPT,
)
from .output.output_format_prompt import OUTPUT_FORMAT_PROMPT
from .system_prompt_template import (
    IDENTITY_PROMPT,
    CAPABILITIES_PROMPT,
    CORE_COMPETENCIES_PROMPT,
    DESIGN_PRINCIPLES_PROMPT,
    RULES_PROMPT,
    PRODUCTION_READINESS_PROMPT,
    OUTPUT_FORMAT_PROMPT as XML_OUTPUT_FORMAT_PROMPT,
    build_system_prompt,
    build_generation_prompt,
    build_review_prompt,
    build_debug_prompt,
    build_chat_prompt,
)
from .performance import (
    CACHING_PROMPT,
    DISASTER_RECOVERY_PROMPT,
    LOAD_BALANCING_PROMPT,
    MESSAGE_QUEUE_PROMPT,
    PERFORMANCE_PROMPTS,
    SCALING_PROMPT,
)
from .principles import (
    CLEAN_CODE_PROMPT,
    DESIGN_PATTERNS_PROMPT,
    DRY_KISS_YAGNI_PROMPT,
    PRINCIPLES_PROMPTS,
    SOLID_PROMPT,
)
from .security import (
    ENCRYPTION_PROMPT,
    OWASP_PROMPT,
    RBAC_PROMPT,
    SECRETS_MANAGEMENT_PROMPT,
    SECURITY_PROMPTS,
    VULNERABILITY_SCANNING_PROMPT,
)
from .testing import (
    CONTRACT_TESTING_PROMPT,
    E2E_TESTING_PROMPT,
    INTEGRATION_TESTING_PROMPT,
    LOAD_TESTING_PROMPT,
    TDD_BDD_PROMPT,
    TESTING_PROMPTS,
    UNIT_TESTING_PROMPT,
)

__all__ = [
    # Master
    "MASTER_PROMPT",
    "OUTPUT_FORMAT_PROMPT",
    # API
    "API_PROMPTS",
    "REST_PROMPT",
    "GRAPHQL_PROMPT",
    "GRPC_PROMPT",
    "PAGINATION_PROMPT",
    "RATE_LIMITING_PROMPT",
    "VERSIONING_PROMPT",
    # Architecture
    "ARCHITECTURE_PROMPTS",
    "MONOLITHIC_PROMPT",
    "MICROSERVICES_PROMPT",
    "CQRS_PROMPT",
    "DDD_PROMPT",
    "EVENT_DRIVEN_PROMPT",
    "SERVERLESS_PROMPT",
    # Auth
    "AUTH_PROMPTS",
    "JWT_PROMPT",
    "OAUTH2_PROMPT",
    "LDAP_PROMPT",
    "MFA_PROMPT",
    "SESSION_MANAGEMENT_PROMPT",
    "SSO_PROMPT",
    # Database
    "DATABASE_PROMPTS",
    "SQL_PROMPT",
    "NOSQL_PROMPT",
    "INDEXING_PROMPT",
    "SCHEMA_DESIGN_PROMPT",
    "SHARDING_REPLICATION_PROMPT",
    "TRANSACTIONS_PROMPT",
    # DevOps
    "DEVOPS_PROMPTS",
    "DOCKER_PROMPT",
    "CICD_PROMPT",
    "KUBERNETES_PROMPT",
    "TERRAFORM_PROMPT",
    "MONITORING_PROMPT",
    "CLOUD_AWS_PROMPT",
    "CLOUD_AZURE_PROMPT",
    "CLOUD_GCP_PROMPT",
    # Frameworks
    "FRAMEWORK_PROMPTS",
    "FASTAPI_PROMPT",
    "EXPRESS_PROMPT",
    "SPRING_PROMPT",
    "NESTJS_PROMPT",
    "DJANGO_PROMPT",
    "FLASK_PROMPT",
    "GIN_PROMPT",
    "DOTNET_PROMPT",
    # Languages
    "LANGUAGE_PROMPTS",
    "PYTHON_PROMPT",
    "TYPESCRIPT_PROMPT",
    "JAVA_PROMPT",
    "GO_PROMPT",
    "CSHARP_PROMPT",
    "RUST_PROMPT",
    # Security
    "SECURITY_PROMPTS",
    "OWASP_PROMPT",
    "ENCRYPTION_PROMPT",
    "RBAC_PROMPT",
    "SECRETS_MANAGEMENT_PROMPT",
    "VULNERABILITY_SCANNING_PROMPT",
    # Testing
    "TESTING_PROMPTS",
    "UNIT_TESTING_PROMPT",
    "INTEGRATION_TESTING_PROMPT",
    "E2E_TESTING_PROMPT",
    "LOAD_TESTING_PROMPT",
    "CONTRACT_TESTING_PROMPT",
    "TDD_BDD_PROMPT",
    # Performance
    "PERFORMANCE_PROMPTS",
    "CACHING_PROMPT",
    "SCALING_PROMPT",
    "LOAD_BALANCING_PROMPT",
    "MESSAGE_QUEUE_PROMPT",
    "DISASTER_RECOVERY_PROMPT",
    # Principles
    "PRINCIPLES_PROMPTS",
    "SOLID_PROMPT",
    "CLEAN_CODE_PROMPT",
    "DRY_KISS_YAGNI_PROMPT",
    "DESIGN_PATTERNS_PROMPT",
    # ML/Inference
    "ML_INFERENCE_PROMPTS",
    "MODEL_SERVING_PROMPT",
    "RAG_PROMPT",
    "VECTOR_DB_PROMPT",
    "INFERENCE_OPTIMIZATION_PROMPT",
    # XML Template Functions
    "IDENTITY_PROMPT",
    "CAPABILITIES_PROMPT",
    "CORE_COMPETENCIES_PROMPT",
    "DESIGN_PRINCIPLES_PROMPT",
    "RULES_PROMPT",
    "PRODUCTION_READINESS_PROMPT",
    "build_system_prompt",
    "build_generation_prompt",
    "build_review_prompt",
    "build_debug_prompt",
    "build_chat_prompt",
]
