# MariaDB converter
"""
MariaDB Converter (MySQL fork with enhancements)
"""

from datetime import datetime
from database_generation.converters.base import BaseConverter
from database_generation.db_types import (
    ForgeSchema,
    EntityDef,
    FieldDef,
    FieldType,
    EditorType
)


class MariaDBConverter(BaseConverter):
    """Converts ForgeSchema to MariaDB DDL"""
    
    TYPE_MAP = {
        FieldType.UUID: "CHAR(36)",
        FieldType.STRING: "VARCHAR",
        FieldType.TEXT: "TEXT",
        FieldType.INTEGER: "INT",
        FieldType.BIGINT: "BIGINT",
        FieldType.DECIMAL: "DECIMAL",
        FieldType.FLOAT: "DOUBLE",
        FieldType.BOOLEAN: "BOOLEAN",
        FieldType.DATE: "DATE",
        FieldType.TIME: "TIME",
        FieldType.TIMESTAMP: "TIMESTAMP",
        FieldType.JSON: "JSON",
        FieldType.ARRAY: "JSON",
        FieldType.ENUM: "VARCHAR(50)",
        FieldType.BINARY: "BLOB",
    }
    
    def convert(self, schema: ForgeSchema) -> str:
        """Convert schema to MariaDB DDL"""
        
        parts = [
            self._header(schema),
            self._tables(schema),
            self._indexes(schema),
            self._triggers(schema),
            self._footer()
        ]
        
        return "\n\n".join(filter(None, parts))
    
    def _header(self, schema: ForgeSchema) -> str:
        return f"""-- MariaDB Schema
-- Generated by FORGE on {datetime.now().isoformat()}
-- Version: {schema.version}

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;"""
    
    def _tables(self, schema: ForgeSchema) -> str:
        tables = []
        for entity in schema.entities:
            table_ddl = self._create_table(entity)
            tables.append(table_ddl)
        return "\n\n".join(tables)
    
    def _create_table(self, entity: EntityDef) -> str:
        cols = []
        constraints = []
        
        # Fields
        for field in entity.fields:
            col = self._field_to_column(field)
            cols.append(f"    {col}")
        
        # Primary key
        pk_fields = [f.name for f in entity.fields if f.primary_key]
        if pk_fields:
            constraints.append(f"    PRIMARY KEY ({', '.join(pk_fields)})")
        
        # Unique constraints
        unique_fields = [f for f in entity.fields if f.unique and not f.primary_key]
        for field in unique_fields:
            constraints.append(f"    UNIQUE KEY uk_{entity.name}_{field.name} ({field.name})")
        
        # Foreign keys
        for field in entity.fields:
            if field.reference:
                ref = field.reference
                fk_name = f"fk_{entity.name}_{field.name}"
                fk_def = f"    CONSTRAINT {fk_name} FOREIGN KEY ({field.name}) REFERENCES {ref.entity}({ref.field})"
                fk_def += f" ON DELETE {ref.on_delete.value.upper()}"
                fk_def += f" ON UPDATE {ref.on_update.value.upper()}"
                constraints.append(fk_def)
        
        all_parts = cols + constraints
        
        return f"""CREATE TABLE `{entity.name}` (
{','.join(all_parts)}
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;"""
    
    def _field_to_column(self, field: FieldDef) -> str:
        parts = [f"`{field.name}`"]
        
        # Data type
        base_type = self.TYPE_MAP.get(field.type, "VARCHAR(255)")
        
        # Length for strings
        if field.type == FieldType.STRING and field.length:
            parts.append(f"{base_type}({field.length})")
        elif field.type == FieldType.DECIMAL and field.precision:
            scale = field.scale or 2
            parts.append(f"{base_type}({field.precision},{scale})")
        else:
            if base_type == "VARCHAR" and "(" not in base_type:
                parts.append(f"{base_type}(255)")
            else:
                parts.append(base_type)
        
        # Auto increment (for INTEGER primary keys)
        if field.primary_key and field.type == FieldType.INTEGER:
            parts.append("AUTO_INCREMENT")
        
        # Not null
        if field.required or field.primary_key:
            parts.append("NOT NULL")
        else:
            parts.append("NULL")
        
        # Default
        if field.default is not None:
            if isinstance(field.default, str):
                if field.default.upper() in ('CURRENT_TIMESTAMP', 'NOW()', 'UUID()'):
                    parts.append(f"DEFAULT {field.default}")
                else:
                    parts.append(f"DEFAULT '{field.default}'")
            elif isinstance(field.default, bool):
                parts.append(f"DEFAULT {int(field.default)}")
            else:
                parts.append(f"DEFAULT {field.default}")
        elif field.type == FieldType.TIMESTAMP and field.name == 'created_at':
            parts.append("DEFAULT CURRENT_TIMESTAMP")
        elif field.type == FieldType.TIMESTAMP and field.name == 'updated_at':
            parts.append("DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
        
        # Comment
        if field.comment:
            parts.append(f"COMMENT '{field.comment}'")
        
        return " ".join(parts)
    
    def _indexes(self, schema: ForgeSchema) -> str:
        indexes = []
        
        for entity in schema.entities:
            # Entity-level indexes
            for idx in entity.indexes:
                idx_name = idx.name or f"idx_{entity.name}_{'_'.join(idx.fields)}"
                idx_cols = ", ".join([f"`{f}`" for f in idx.fields])
                unique = "UNIQUE " if idx.unique else ""
                indexes.append(f"CREATE {unique}INDEX {idx_name} ON `{entity.name}`({idx_cols});")
        
        return "\n".join(indexes) if indexes else ""
    
    def _triggers(self, schema: ForgeSchema) -> str:
        triggers = []
        
        for entity in schema.entities:
            # MariaDB supports auto-update for timestamps via column definition
            # Only need triggers for custom logic
            pass
        
        return "\n\n".join(triggers) if triggers else ""
    
    def _footer(self) -> str:
        return "-- End of schema"
    
    def format_for_editor(self, ddl: str, editor: EditorType) -> str:
        """Format DDL for specific editor"""
        return ddl
