# Oracle converter
"""
Oracle Database Converter
"""

from datetime import datetime
from database_generation.converters.base import BaseConverter
from database_generation.db_types import (
    ForgeSchema,
    EntityDef,
    FieldDef,
    FieldType,
    EditorType
)


class OracleConverter(BaseConverter):
    """Converts ForgeSchema to Oracle DDL"""
    
    TYPE_MAP = {
        FieldType.UUID: "RAW(16)",
        FieldType.STRING: "VARCHAR2",
        FieldType.TEXT: "CLOB",
        FieldType.INTEGER: "NUMBER(10)",
        FieldType.BIGINT: "NUMBER(19)",
        FieldType.DECIMAL: "NUMBER",
        FieldType.FLOAT: "BINARY_DOUBLE",
        FieldType.BOOLEAN: "NUMBER(1)",
        FieldType.DATE: "DATE",
        FieldType.TIME: "TIMESTAMP",
        FieldType.TIMESTAMP: "TIMESTAMP",
        FieldType.JSON: "CLOB",
        FieldType.ARRAY: "CLOB",
        FieldType.ENUM: "VARCHAR2(50)",
        FieldType.BINARY: "BLOB",
    }
    
    def convert(self, schema: ForgeSchema) -> str:
        """Convert schema to Oracle DDL"""
        
        parts = [
            self._header(schema),
            self._sequences(schema),
            self._tables(schema),
            self._indexes(schema),
            self._triggers(schema),
            self._footer()
        ]
        
        return "\n\n".join(filter(None, parts))
    
    def _header(self, schema: ForgeSchema) -> str:
        return f"""-- Oracle Database Schema
-- Generated by FORGE on {datetime.now().isoformat()}
-- Version: {schema.version}

SET DEFINE OFF;"""
    
    def _sequences(self, schema: ForgeSchema) -> str:
        """Create sequences for auto-increment fields (INTEGER primary keys)"""
        sequences = []
        
        for entity in schema.entities:
            # Only create sequences for INTEGER primary key fields
            auto_fields = [f for f in entity.fields if f.primary_key and f.type == FieldType.INTEGER]
            for field in auto_fields:
                seq_name = f"seq_{entity.name}_{field.name}"
                sequences.append(f"CREATE SEQUENCE {seq_name} START WITH 1 INCREMENT BY 1;")
        
        return "\n".join(sequences) if sequences else ""
    
    def _tables(self, schema: ForgeSchema) -> str:
        tables = []
        for entity in schema.entities:
            table_ddl = self._create_table(entity)
            tables.append(table_ddl)
        return "\n\n".join(tables)
    
    def _create_table(self, entity: EntityDef) -> str:
        cols = []
        constraints = []
        
        # Fields
        for field in entity.fields:
            col = self._field_to_column(field)
            cols.append(f"    {col}")
        
        # Primary key
        pk_fields = [f.name for f in entity.fields if f.primary_key]
        if pk_fields:
            pk_name = f"pk_{entity.name}"
            constraints.append(f"    CONSTRAINT {pk_name} PRIMARY KEY ({', '.join(pk_fields)})")
        
        # Unique constraints
        unique_fields = [f for f in entity.fields if f.unique and not f.primary_key]
        for field in unique_fields:
            uk_name = f"uk_{entity.name}_{field.name}"
            constraints.append(f"    CONSTRAINT {uk_name} UNIQUE ({field.name})")
        
        # Foreign keys
        for field in entity.fields:
            if field.reference:
                ref = field.reference
                fk_name = f"fk_{entity.name}_{field.name}"
                fk_def = f"    CONSTRAINT {fk_name} FOREIGN KEY ({field.name}) REFERENCES {ref.entity}({ref.field})"
                fk_def += f" ON DELETE {ref.on_delete.value.upper()}"
                constraints.append(fk_def)
        
        all_parts = cols + constraints
        
        return f"""CREATE TABLE {entity.name} (
{','.join(all_parts)}
);"""
    
    def _field_to_column(self, field: FieldDef) -> str:
        parts = [field.name]
        
        # Data type
        base_type = self.TYPE_MAP.get(field.type, "VARCHAR2(255)")
        
        # Length for strings
        if field.type == FieldType.STRING and field.length:
            parts.append(f"{base_type}({field.length})")
        elif field.type == FieldType.DECIMAL and field.precision:
            scale = field.scale or 2
            parts.append(f"{base_type}({field.precision},{scale})")
        else:
            if base_type == "VARCHAR2" and "(" not in base_type:
                parts.append(f"{base_type}(255)")
            else:
                parts.append(base_type)
        
        # Not null
        if field.required or field.primary_key:
            parts.append("NOT NULL")
        
        # Default
        if field.default is not None:
            if isinstance(field.default, str):
                if field.default.upper() in ('SYS_GUID()', 'SYSDATE', 'SYSTIMESTAMP'):
                    parts.append(f"DEFAULT {field.default}")
                else:
                    parts.append(f"DEFAULT '{field.default}'")
            elif isinstance(field.default, bool):
                parts.append(f"DEFAULT {int(field.default)}")
            else:
                parts.append(f"DEFAULT {field.default}")
        elif field.type == FieldType.UUID:
            parts.append("DEFAULT SYS_GUID()")
        elif field.type == FieldType.TIMESTAMP and field.name in ('created_at', 'updated_at'):
            parts.append("DEFAULT SYSTIMESTAMP")
        
        return " ".join(parts)
    
    def _indexes(self, schema: ForgeSchema) -> str:
        indexes = []
        
        for entity in schema.entities:
            # Entity-level indexes
            for idx in entity.indexes:
                idx_name = idx.name or f"idx_{entity.name}_{'_'.join(idx.fields)}"
                idx_cols = ", ".join(idx.fields)
                unique = "UNIQUE " if idx.unique else ""
                indexes.append(f"CREATE {unique}INDEX {idx_name} ON {entity.name}({idx_cols});")
        
        return "\n".join(indexes) if indexes else ""
    
    def _triggers(self, schema: ForgeSchema) -> str:
        triggers = []
        
        for entity in schema.entities:
            # Auto-increment triggers (for INTEGER primary keys)
            auto_fields = [f for f in entity.fields if f.primary_key and f.type == FieldType.INTEGER]
            for field in auto_fields:
                seq_name = f"seq_{entity.name}_{field.name}"
                trigger = f"""CREATE OR REPLACE TRIGGER trg_{entity.name}_{field.name}
BEFORE INSERT ON {entity.name}
FOR EACH ROW
BEGIN
    IF :NEW.{field.name} IS NULL THEN
        SELECT {seq_name}.NEXTVAL INTO :NEW.{field.name} FROM DUAL;
    END IF;
END;
/"""
                triggers.append(trigger)
            
            # Auto-update timestamps
            updated_field = next(
                (f for f in entity.fields if f.name in ('updated_at', 'modified_at')),
                None
            )
            
            if updated_field:
                trigger = f"""CREATE OR REPLACE TRIGGER trg_{entity.name}_update
BEFORE UPDATE ON {entity.name}
FOR EACH ROW
BEGIN
    :NEW.{updated_field.name} := SYSTIMESTAMP;
END;
/"""
                triggers.append(trigger)
        
        return "\n\n".join(triggers) if triggers else ""
    
    def _footer(self) -> str:
        return "-- End of schema"
    
    def format_for_editor(self, ddl: str, editor: EditorType) -> str:
        """Format DDL for specific editor"""
        return ddl
