# SQLite converter
"""
SQLite Converter
"""

from datetime import datetime
from database_generation.converters.base import BaseConverter
from database_generation.db_types import (
    ForgeSchema,
    EntityDef,
    FieldDef,
    FieldType,
    EditorType
)


class SQLiteConverter(BaseConverter):
    """Converts ForgeSchema to SQLite DDL"""
    
    TYPE_MAP = {
        FieldType.UUID: "TEXT",
        FieldType.STRING: "TEXT",
        FieldType.TEXT: "TEXT",
        FieldType.INTEGER: "INTEGER",
        FieldType.BIGINT: "INTEGER",
        FieldType.DECIMAL: "REAL",
        FieldType.FLOAT: "REAL",
        FieldType.BOOLEAN: "INTEGER",
        FieldType.DATE: "TEXT",
        FieldType.TIME: "TEXT",
        FieldType.TIMESTAMP: "TEXT",
        FieldType.JSON: "TEXT",
        FieldType.ARRAY: "TEXT",
        FieldType.ENUM: "TEXT",
        FieldType.BINARY: "BLOB",
    }
    
    def convert(self, schema: ForgeSchema) -> str:
        """Convert schema to SQLite DDL"""
        
        parts = [
            self._header(schema),
            self._tables(schema),
            self._indexes(schema),
            self._triggers(schema),
            self._footer()
        ]
        
        return "\n\n".join(filter(None, parts))
    
    def _header(self, schema: ForgeSchema) -> str:
        return f"""-- SQLite Schema
-- Generated by FORGE on {datetime.now().isoformat()}
-- Version: {schema.version}

PRAGMA foreign_keys = ON;
PRAGMA encoding = 'UTF-8';"""
    
    def _tables(self, schema: ForgeSchema) -> str:
        tables = []
        for entity in schema.entities:
            table_ddl = self._create_table(entity)
            tables.append(table_ddl)
        return "\n\n".join(tables)
    
    def _create_table(self, entity: EntityDef) -> str:
        cols = []
        
        # Fields
        for field in entity.fields:
            col = self._field_to_column(field)
            cols.append(f"    {col}")
        
        # Primary key
        pk_fields = [f.name for f in entity.fields if f.primary_key]
        if pk_fields:
            cols.append(f"    PRIMARY KEY ({', '.join(pk_fields)})")
        
        # Foreign keys
        for field in entity.fields:
            if field.reference:
                ref = field.reference
                fk_def = f"    FOREIGN KEY ({field.name}) REFERENCES {ref.entity}({ref.field})"
                fk_def += f" ON DELETE {ref.on_delete.value.upper()}"
                fk_def += f" ON UPDATE {ref.on_update.value.upper()}"
                cols.append(fk_def)
        
        return f"""CREATE TABLE {entity.name} (
{','.join(cols)}
);"""
    
    def _field_to_column(self, field: FieldDef) -> str:
        parts = [field.name]
        
        # Data type
        base_type = self.TYPE_MAP.get(field.type, "TEXT")
        
        # Length for strings (SQLite ignores but good for documentation)
        if field.type == FieldType.STRING and field.length:
            parts.append(f"{base_type}({field.length})")
        else:
            parts.append(base_type)
        
        # Primary key with autoincrement (for INTEGER only)
        if field.primary_key and field.type == FieldType.INTEGER:
            parts.append("PRIMARY KEY AUTOINCREMENT")
        
        # Not null
        if field.required and not field.primary_key:
            parts.append("NOT NULL")
        
        # Unique
        if field.unique:
            parts.append("UNIQUE")
        
        # Default
        if field.default is not None:
            if isinstance(field.default, str):
                parts.append(f"DEFAULT '{field.default}'")
            elif isinstance(field.default, bool):
                parts.append(f"DEFAULT {int(field.default)}")
            else:
                parts.append(f"DEFAULT {field.default}")
        
        return " ".join(parts)
    
    def _indexes(self, schema: ForgeSchema) -> str:
        indexes = []
        
        for entity in schema.entities:
            # Entity-level indexes
            for idx in entity.indexes:
                idx_name = idx.name or f"idx_{entity.name}_{'_'.join(idx.fields)}"
                idx_cols = ", ".join(idx.fields)
                unique = "UNIQUE " if idx.unique else ""
                indexes.append(f"CREATE {unique}INDEX {idx_name} ON {entity.name}({idx_cols});")
        
        return "\n".join(indexes) if indexes else ""
    
    def _triggers(self, schema: ForgeSchema) -> str:
        triggers = []
        
        for entity in schema.entities:
            # Auto-update timestamps
            has_updated_at = any(
                f.name in ('updated_at', 'modified_at') 
                for f in entity.fields
            )
            
            if has_updated_at:
                trigger = f"""CREATE TRIGGER update_{entity.name}_timestamp
AFTER UPDATE ON {entity.name}
FOR EACH ROW
BEGIN
    UPDATE {entity.name} SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;"""
                triggers.append(trigger)
        
        return "\n\n".join(triggers) if triggers else ""
    
    def _footer(self) -> str:
        return "-- End of schema"
    
    def format_for_editor(self, ddl: str, editor: EditorType) -> str:
        """Format DDL for specific editor"""
        return ddl
