# SQL Server converter
"""
Microsoft SQL Server Converter
"""

from datetime import datetime
from database_generation.converters.base import BaseConverter
from database_generation.db_types import (
    ForgeSchema,
    EntityDef,
    FieldDef,
    FieldType,
    EditorType
)


class SQLServerConverter(BaseConverter):
    """Converts ForgeSchema to SQL Server DDL"""
    
    TYPE_MAP = {
        FieldType.UUID: "UNIQUEIDENTIFIER",
        FieldType.STRING: "NVARCHAR",
        FieldType.TEXT: "NVARCHAR(MAX)",
        FieldType.INTEGER: "INT",
        FieldType.BIGINT: "BIGINT",
        FieldType.DECIMAL: "DECIMAL",
        FieldType.FLOAT: "FLOAT",
        FieldType.BOOLEAN: "BIT",
        FieldType.DATE: "DATE",
        FieldType.TIME: "TIME",
        FieldType.TIMESTAMP: "DATETIME2",
        FieldType.JSON: "NVARCHAR(MAX)",
        FieldType.ARRAY: "NVARCHAR(MAX)",
        FieldType.ENUM: "NVARCHAR(50)",
        FieldType.BINARY: "VARBINARY(MAX)",
    }
    
    def convert(self, schema: ForgeSchema) -> str:
        """Convert schema to SQL Server DDL"""
        
        parts = [
            self._header(schema),
            self._tables(schema),
            self._indexes(schema),
            self._triggers(schema),
            self._footer()
        ]
        
        return "\n\n".join(filter(None, parts))
    
    def _header(self, schema: ForgeSchema) -> str:
        return f"""-- SQL Server Schema
-- Generated by FORGE on {datetime.now().isoformat()}
-- Version: {schema.version}

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO"""
    
    def _tables(self, schema: ForgeSchema) -> str:
        tables = []
        for entity in schema.entities:
            table_ddl = self._create_table(entity)
            tables.append(table_ddl)
        return "\n\nGO\n\n".join(tables)
    
    def _create_table(self, entity: EntityDef) -> str:
        cols = []
        constraints = []
        
        # Fields
        for field in entity.fields:
            col = self._field_to_column(field)
            cols.append(f"    {col}")
        
        # Primary key
        pk_fields = [f.name for f in entity.fields if f.primary_key]
        if pk_fields:
            pk_name = f"PK_{entity.name}"
            constraints.append(f"    CONSTRAINT {pk_name} PRIMARY KEY CLUSTERED ({', '.join(pk_fields)})")
        
        # Unique constraints
        unique_fields = [f for f in entity.fields if f.unique and not f.primary_key]
        for field in unique_fields:
            uk_name = f"UQ_{entity.name}_{field.name}"
            constraints.append(f"    CONSTRAINT {uk_name} UNIQUE ({field.name})")
        
        # Foreign keys
        for field in entity.fields:
            if field.reference:
                ref = field.reference
                fk_name = f"FK_{entity.name}_{field.name}"
                fk_def = f"    CONSTRAINT {fk_name} FOREIGN KEY ({field.name}) REFERENCES {ref.entity}({ref.field})"
                fk_def += f" ON DELETE {ref.on_delete.value.upper()}"
                fk_def += f" ON UPDATE {ref.on_update.value.upper()}"
                constraints.append(fk_def)
        
        all_parts = cols + constraints
        
        return f"""CREATE TABLE [dbo].[{entity.name}] (
{','.join(all_parts)}
);"""
    
    def _field_to_column(self, field: FieldDef) -> str:
        parts = [f"[{field.name}]"]
        
        # Data type
        base_type = self.TYPE_MAP.get(field.type, "NVARCHAR(255)")
        
        # Length for strings
        if field.type == FieldType.STRING and field.length:
            parts.append(f"{base_type}({field.length})")
        elif field.type == FieldType.DECIMAL and field.precision:
            scale = field.scale or 2
            parts.append(f"{base_type}({field.precision},{scale})")
        else:
            if base_type == "NVARCHAR" and "(" not in base_type:
                parts.append(f"{base_type}(255)")
            else:
                parts.append(base_type)
        
        # Identity (for INTEGER primary keys)
        if field.primary_key and field.type == FieldType.INTEGER:
            parts.append("IDENTITY(1,1)")
        
        # Not null
        if field.required or field.primary_key:
            parts.append("NOT NULL")
        else:
            parts.append("NULL")
        
        # Default
        if field.default is not None:
            if isinstance(field.default, str):
                if field.default.upper() in ('NEWID()', 'GETDATE()', 'GETUTCDATE()'):
                    parts.append(f"DEFAULT {field.default}")
                else:
                    parts.append(f"DEFAULT '{field.default}'")
            elif isinstance(field.default, bool):
                parts.append(f"DEFAULT {int(field.default)}")
            else:
                parts.append(f"DEFAULT {field.default}")
        elif field.type == FieldType.UUID:
            parts.append("DEFAULT NEWID()")
        
        return " ".join(parts)
    
    def _indexes(self, schema: ForgeSchema) -> str:
        indexes = []
        
        for entity in schema.entities:
            # Entity-level indexes
            for idx in entity.indexes:
                idx_name = idx.name or f"IX_{entity.name}_{'_'.join(idx.fields)}"
                idx_cols = ", ".join([f"[{f}]" for f in idx.fields])
                unique = "UNIQUE " if idx.unique else ""
                indexes.append(f"CREATE {unique}INDEX {idx_name} ON [dbo].[{entity.name}]({idx_cols});")
        
        return "\n".join(indexes) if indexes else ""
    
    def _triggers(self, schema: ForgeSchema) -> str:
        triggers = []
        
        for entity in schema.entities:
            # Auto-update timestamps
            updated_field = next(
                (f for f in entity.fields if f.name in ('updated_at', 'modified_at')),
                None
            )
            
            if updated_field:
                trigger = f"""CREATE TRIGGER trg_{entity.name}_update
ON [dbo].[{entity.name}]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE [dbo].[{entity.name}]
    SET {updated_field.name} = GETUTCDATE()
    FROM [dbo].[{entity.name}] t
    INNER JOIN inserted i ON t.id = i.id;
END;
GO"""
                triggers.append(trigger)
        
        return "\n\n".join(triggers) if triggers else ""
    
    def _footer(self) -> str:
        return "-- End of schema"
    
    def format_for_editor(self, ddl: str, editor: EditorType) -> str:
        """Format DDL for specific editor"""
        return ddl
