"""Schema generator for converting InferredModels to database schemas."""

import asyncio
import json
import logging
from pathlib import Path
from typing import Any

from core.types import InferredField, InferredFieldType, InferredModel, InferredRelation

logger = logging.getLogger(__name__)


class SchemaGenerator:
    """Generate database schemas from inferred models."""

    def __init__(self, output_dir: Path):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _pluralize(self, word: str) -> str:
        """Simple pluralization for table names."""
        # Special cases
        special_plurals = {
            'todo': 'todos',
            'person': 'people',
            'child': 'children',
            'man': 'men',
            'woman': 'women',
        }
        word_lower = word.lower()
        if word_lower in special_plurals:
            return special_plurals[word_lower]
        
        if word.endswith('s') or word.endswith('x') or word.endswith('z') or word.endswith('ch') or word.endswith('sh'):
            return word + 'es'
        elif word.endswith('y') and len(word) > 1 and word[-2] not in 'aeiou':
            return word[:-1] + 'ies'
        elif word.endswith('o') and len(word) > 1 and word[-2] not in 'aeiou' and word.lower() != 'todo':
            return word + 'es'
        else:
            return word + 's'

    async def generate_schema(
        self,
        models: list[InferredModel],
        relations: list[InferredRelation],
        db_type: str = "postgresql",
    ) -> dict[str, Path]:
        """Generate schema files for specified database type."""
        logger.info(f"Generating {db_type} schema for {len(models)} models")

        if db_type in ("postgresql", "mysql", "sqlite", "mariadb", "sqlserver", "oracle"):
            return await self._generate_sql_schema(models, relations, db_type)
        elif db_type == "mongodb":
            return await self._generate_mongodb_schema(models)
        else:
            raise ValueError(f"Unsupported database type: {db_type}")

    async def _generate_sql_schema(
        self,
        models: list[InferredModel],
        relations: list[InferredRelation],
        db_type: str,
    ) -> dict[str, Path]:
        """Generate SQL schema files."""
        schema_lines = []
        index_lines = []

        # Header
        schema_lines.append(f"-- {db_type.upper()} Schema")
        schema_lines.append(f"-- Generated by FORGE")
        schema_lines.append(f"-- Models: {len(models)}\n")

        # Generate CREATE TABLE statements
        for model in models:
            table_sql = self._generate_create_table_with_fk(model, relations, db_type)
            schema_lines.append(table_sql)
            schema_lines.append("")

            # Generate indexes for fields
            table_name = self._pluralize(model.name.lower())
            indexes = getattr(model, 'indexes', [])
            for idx_fields in indexes:
                idx_name = f"idx_{model.name.lower()}_{'_'.join(idx_fields)}"
                idx_sql = f"CREATE INDEX {idx_name} ON {table_name} ({', '.join(idx_fields)});"
                index_lines.append(idx_sql)

            # Add indexes for foreign key fields
            for relation in relations:
                if relation.source_model.lower() == model.name.lower():
                    idx_name = f"idx_{relation.source_model.lower()}_{relation.source_field}"
                    idx_sql = f"CREATE INDEX {idx_name} ON {table_name}({relation.source_field});"
                    if idx_sql not in index_lines:
                        index_lines.append(idx_sql)

        # Add PostgreSQL triggers for updated_at
        if db_type == "postgresql":
            schema_lines.append("-- Function to automatically update updated_at timestamp")
            schema_lines.append("CREATE OR REPLACE FUNCTION update_updated_at_column()")
            schema_lines.append("RETURNS TRIGGER AS $$")
            schema_lines.append("BEGIN")
            schema_lines.append("  NEW.updated_at = CURRENT_TIMESTAMP;")
            schema_lines.append("  RETURN NEW;")
            schema_lines.append("END;")
            schema_lines.append("$$ language 'plpgsql';")
            schema_lines.append("")
            
            schema_lines.append("-- Triggers for automatic updated_at updates")
            for model in models:
                if getattr(model, 'timestamps', False):
                    table_name = self._pluralize(model.name.lower())
                    schema_lines.append(f"CREATE TRIGGER update_{model.name.lower()}_updated_at BEFORE UPDATE ON {table_name}")
                    schema_lines.append("  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
                    schema_lines.append("")

        # Write files
        files = {}
        
        # Add indexes to schema if any
        if index_lines:
            schema_lines.append("\n-- Indexes for better performance")
            schema_lines.extend(index_lines)
        
        # Add performance indexes for common patterns
        schema_lines.append("\n-- Additional performance indexes")
        for model in models:
            table_name = self._pluralize(model.name.lower())
            # Index foreign key fields
            for field in model.fields:
                if field.name.endswith('_id'):
                    idx_name = f"idx_{table_name}_{field.name}"
                    idx_sql = f"CREATE INDEX {idx_name} ON {table_name}({field.name});"
                    if idx_sql not in index_lines:
                        schema_lines.append(idx_sql)
            # Index status/type enum fields
            for field in model.fields:
                if field.name.lower() in ['status', 'type', 'priority', 'state']:
                    idx_name = f"idx_{table_name}_{field.name}"
                    idx_sql = f"CREATE INDEX {idx_name} ON {table_name}({field.name});"
                    if idx_sql not in index_lines:
                        schema_lines.append(idx_sql)
        
        schema_file = self.output_dir / "schema.sql"
        schema_file.write_text("\n".join(schema_lines), encoding="utf-8")
        files["schema"] = schema_file

        logger.info(f"Generated SQL schema files: {list(files.keys())}")
        return files

    def _generate_create_table(self, model: InferredModel, db_type: str) -> str:
        """Generate CREATE TABLE statement."""
        # Use plural table names by default
        table_name = self._pluralize(model.name.lower())
        lines = [f"CREATE TABLE {table_name} ("]
        
        # Fields
        field_definitions = []
        existing_field_names = set()
        
        # Import field normalizer for timestamp detection
        from core.field_normalizer import is_timestamp_field
        
        for field in model.fields:
            # Skip TypeScript timestamp fields - they'll be added as proper SQL timestamps below
            if is_timestamp_field(field.name):
                continue
                
            field_def = self._map_field_to_sql(field, db_type)
            field_definitions.append(f"  {field_def}")
            existing_field_names.add(field.name.lower())

        # Add timestamps if enabled (only if not already present)
        if getattr(model, 'timestamps', False):
            if db_type == "postgresql":
                if 'created_at' not in existing_field_names:
                    field_definitions.append("  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP")
                if 'updated_at' not in existing_field_names:
                    field_definitions.append("  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP")
            elif db_type in ("mysql", "mariadb"):
                if 'created_at' not in existing_field_names:
                    field_definitions.append("  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
                if 'updated_at' not in existing_field_names:
                    field_definitions.append("  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
            else:
                if 'created_at' not in existing_field_names:
                    field_definitions.append("  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
                if 'updated_at' not in existing_field_names:
                    field_definitions.append("  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")

        # Add soft delete if enabled
        if getattr(model, 'soft_delete', False):
            field_definitions.append("  deleted_at TIMESTAMP NULL")

        # Primary key
        primary_key = getattr(model, 'primary_key', 'id')
        field_definitions.append(f"  PRIMARY KEY ({primary_key})")

        # Unique constraints
        unique_constraints = getattr(model, 'unique_constraints', [])
        for unique_fields in unique_constraints:
            field_definitions.append(f"  UNIQUE ({', '.join(unique_fields)})")

        lines.append(",\n".join(field_definitions))
        lines.append(");")

        return "\n".join(lines)

    def _generate_create_table_with_fk(
        self, model: InferredModel, relations: list[InferredRelation], db_type: str
    ) -> str:
        """Generate CREATE TABLE statement with inline foreign keys."""
        # Use plural table names by default
        table_name = self._pluralize(model.name.lower())
        lines = [f"CREATE TABLE {table_name} ("]
        
        # Fields
        field_definitions = []
        existing_field_names = set()
        primary_key = getattr(model, 'primary_key', 'id')
        
        # Check if id field exists
        has_id = any(f.name.lower() == primary_key.lower() for f in model.fields)
        
        # If no id field, add it first
        if not has_id and primary_key == 'id':
            if db_type in ("mysql", "mariadb"):
                field_definitions.append(f"  id INT AUTO_INCREMENT")
            elif db_type == "postgresql":
                field_definitions.append(f"  id SERIAL")
            else:
                field_definitions.append(f"  id INTEGER PRIMARY KEY AUTOINCREMENT")
            existing_field_names.add('id')
        
        for field in model.fields:
            # Add AUTO_INCREMENT for MySQL id fields
            if field.name.lower() == primary_key.lower() and db_type in ("mysql", "mariadb"):
                field_def = self._map_field_to_sql(field, db_type)
                # Add AUTO_INCREMENT if it's the primary key and integer type
                if 'INT' in field_def.upper() and 'AUTO_INCREMENT' not in field_def.upper():
                    field_def = field_def.replace('INT', 'INT AUTO_INCREMENT')
                field_definitions.append(f"  {field_def}")
            else:
                field_def = self._map_field_to_sql(field, db_type)
                field_definitions.append(f"  {field_def}")
            existing_field_names.add(field.name.lower())

        # Add timestamps if enabled (only if not already present)
        if getattr(model, 'timestamps', False):
            if db_type == "postgresql":
                if 'created_at' not in existing_field_names:
                    field_definitions.append("  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP")
                if 'updated_at' not in existing_field_names:
                    field_definitions.append("  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP")
            elif db_type in ("mysql", "mariadb"):
                if 'created_at' not in existing_field_names:
                    field_definitions.append("  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
                if 'updated_at' not in existing_field_names:
                    field_definitions.append("  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
            else:
                if 'created_at' not in existing_field_names:
                    field_definitions.append("  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
                if 'updated_at' not in existing_field_names:
                    field_definitions.append("  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")

        # Add soft delete if enabled
        if getattr(model, 'soft_delete', False):
            field_definitions.append("  deleted_at TIMESTAMP NULL")

        # Primary key
        primary_key = getattr(model, 'primary_key', 'id')
        field_definitions.append(f"  PRIMARY KEY ({primary_key})")

        # Unique constraints
        unique_constraints = getattr(model, 'unique_constraints', [])
        for unique_fields in unique_constraints:
            field_definitions.append(f"  UNIQUE ({', '.join(unique_fields)})")

        # Add inline foreign keys
        for relation in relations:
            if relation.source_model.lower() == model.name.lower():
                target_table = self._pluralize(relation.target_model.lower())
                cascade = "ON DELETE CASCADE" if getattr(relation, 'cascade_delete', False) else "ON DELETE SET NULL"
                fk_constraint = f"  FOREIGN KEY ({relation.source_field}) REFERENCES {target_table}({relation.target_field}) {cascade}"
                field_definitions.append(fk_constraint)
        
        # Add foreign keys for fields ending with _id (inferred relationships)
        for field in model.fields:
            if field.name.endswith('_id'):
                # Infer the target table
                base_name = field.name[:-3]  # Remove '_id'
                target_table = self._pluralize(base_name.lower())
                # Check if this is a valid relation (not already added)
                existing_fks = [f for f in field_definitions if f.strip().startswith('FOREIGN KEY')]
                fk_exists = any(field.name in fk for fk in existing_fks)
                if not fk_exists:
                    fk_constraint = f"  FOREIGN KEY ({field.name}) REFERENCES {target_table}(id) ON DELETE CASCADE"
                    field_definitions.append(fk_constraint)

        lines.append(",\n".join(field_definitions))
        lines.append(");")

        return "\n".join(lines)

    def _map_field_to_sql(self, field: InferredField, db_type: str) -> str:
        """Map InferredField to SQL column definition."""
        # Get base type
        sql_type = self._map_field_type(getattr(field, 'field_type', 'STRING'), db_type)

        # Build column definition
        parts = [field.name, sql_type]

        # For email fields, add UNIQUE constraint
        field_name_lower = field.name.lower()
        if 'email' in field_name_lower:
            if not getattr(field, 'unique', False):
                field.unique = True
        
        # For password fields, ensure NOT NULL
        if 'password' in field_name_lower or 'hash' in field_name_lower:
            if getattr(field, 'nullable', True):
                field.nullable = False

        # NOT NULL - make required fields NOT NULL
        if not getattr(field, 'nullable', True) or field_name_lower in ['username', 'email', 'title']:
            parts.append("NOT NULL")

        # UNIQUE
        if getattr(field, 'unique', False):
            parts.append("UNIQUE")

        # DEFAULT
        default_value = getattr(field, 'default', None)
        if default_value is not None:
            if isinstance(default_value, str):
                parts.append(f"DEFAULT '{default_value}'")
            elif isinstance(default_value, bool):
                if db_type == "postgresql":
                    parts.append(f"DEFAULT {str(default_value).upper()}")
                else:
                    parts.append(f"DEFAULT {1 if default_value else 0}")
            else:
                parts.append(f"DEFAULT {default_value}")

        return " ".join(parts)

    def _map_field_type(self, field_type, db_type: str) -> str:
        """Map InferredFieldType to database-specific SQL type."""
        # Convert string to enum if needed
        if isinstance(field_type, str):
            try:
                from core.types import InferredFieldType
                # FIX: Don't call .upper() - enum values are lowercase!
                field_type = InferredFieldType(field_type.lower())
            except (ValueError, AttributeError):
                field_type = InferredFieldType.STRING
        
        # PostgreSQL types
        if db_type == "postgresql":
            type_map = {
                InferredFieldType.STRING: "VARCHAR(255)",
                InferredFieldType.TEXT: "TEXT",
                InferredFieldType.INTEGER: "INTEGER",
                InferredFieldType.FLOAT: "REAL",
                InferredFieldType.DECIMAL: "DECIMAL(10, 2)",
                InferredFieldType.BOOLEAN: "BOOLEAN",
                InferredFieldType.DATE: "DATE",
                InferredFieldType.DATETIME: "TIMESTAMP WITH TIME ZONE",
                InferredFieldType.JSON: "JSONB",
                InferredFieldType.UUID: "UUID",
                InferredFieldType.ENUM: "VARCHAR(50)",
                InferredFieldType.RELATION: "INTEGER",
            }
        # MySQL/MariaDB types
        elif db_type in ("mysql", "mariadb"):
            type_map = {
                InferredFieldType.STRING: "VARCHAR(255)",
                InferredFieldType.TEXT: "TEXT",
                InferredFieldType.INTEGER: "INT",
                InferredFieldType.FLOAT: "FLOAT",
                InferredFieldType.DECIMAL: "DECIMAL(10, 2)",
                InferredFieldType.BOOLEAN: "TINYINT(1)",
                InferredFieldType.DATE: "DATE",
                InferredFieldType.DATETIME: "DATETIME",
                InferredFieldType.JSON: "JSON",
                InferredFieldType.UUID: "CHAR(36)",
                InferredFieldType.ENUM: "VARCHAR(50)",
                InferredFieldType.RELATION: "INT",
            }
        # SQLite types
        elif db_type == "sqlite":
            type_map = {
                InferredFieldType.STRING: "TEXT",
                InferredFieldType.TEXT: "TEXT",
                InferredFieldType.INTEGER: "INTEGER",
                InferredFieldType.FLOAT: "REAL",
                InferredFieldType.DECIMAL: "REAL",
                InferredFieldType.BOOLEAN: "INTEGER",
                InferredFieldType.DATE: "TEXT",
                InferredFieldType.DATETIME: "TEXT",
                InferredFieldType.JSON: "TEXT",
                InferredFieldType.UUID: "TEXT",
                InferredFieldType.ENUM: "TEXT",
                InferredFieldType.RELATION: "INTEGER",
            }
        else:
            # Default fallback
            type_map = {
                InferredFieldType.STRING: "VARCHAR(255)",
                InferredFieldType.TEXT: "TEXT",
                InferredFieldType.INTEGER: "INTEGER",
                InferredFieldType.FLOAT: "FLOAT",
                InferredFieldType.DECIMAL: "DECIMAL(10, 2)",
                InferredFieldType.BOOLEAN: "BOOLEAN",
                InferredFieldType.DATE: "DATE",
                InferredFieldType.DATETIME: "TIMESTAMP",
                InferredFieldType.JSON: "TEXT",
                InferredFieldType.UUID: "VARCHAR(36)",
                InferredFieldType.ENUM: "VARCHAR(50)",
                InferredFieldType.RELATION: "INTEGER",
            }

        return type_map.get(field_type, "VARCHAR(255)")

    def _generate_foreign_key(self, relation: InferredRelation, db_type: str) -> str:
        """Generate foreign key constraint."""
        fk_name = f"fk_{relation.source_model}_{relation.target_model}"
        
        cascade = "ON DELETE CASCADE" if relation.cascade_delete else "ON DELETE SET NULL"
        
        sql = f"""ALTER TABLE {relation.source_model.lower()} 
    ADD CONSTRAINT {fk_name} 
    FOREIGN KEY ({relation.source_field}) 
    REFERENCES {relation.target_model.lower()}({relation.target_field}) 
    {cascade};"""
        
        return sql

    async def _generate_mongodb_schema(self, models: list[InferredModel]) -> dict[str, Path]:
        """Generate MongoDB schema (validation rules)."""
        files = {}

        for model in models:
            schema = {
                "bsonType": "object",
                "required": [f.name for f in model.fields if not f.nullable],
                "properties": {},
            }

            for field in model.fields:
                field_schema = self._map_field_to_bson(field)
                schema["properties"][field.name] = field_schema

            # Add timestamps
            if model.timestamps:
                schema["properties"]["created_at"] = {"bsonType": "date"}
                schema["properties"]["updated_at"] = {"bsonType": "date"}

            # Write validation schema
            schema_file = self.output_dir / f"{model.name.lower()}_schema.json"
            schema_file.write_text(json.dumps(schema, indent=2), encoding="utf-8")
            files[model.name] = schema_file

        logger.info(f"Generated MongoDB schemas for {len(models)} collections")
        return files

    def _map_field_to_bson(self, field: InferredField) -> dict[str, Any]:
        """Map InferredField to MongoDB BSON type."""
        type_map = {
            InferredFieldType.STRING: "string",
            InferredFieldType.TEXT: "string",
            InferredFieldType.INTEGER: "int",
            InferredFieldType.FLOAT: "double",
            InferredFieldType.DECIMAL: "decimal",
            InferredFieldType.BOOLEAN: "bool",
            InferredFieldType.DATE: "date",
            InferredFieldType.DATETIME: "date",
            InferredFieldType.JSON: "object",
            InferredFieldType.UUID: "string",
            InferredFieldType.ENUM: "string",
            InferredFieldType.RELATION: "int",
        }

        bson_type = type_map.get(field.field_type, "string")
        
        field_schema = {"bsonType": bson_type}

        return field_schema
